# Supabase Configuration
SUPABASE_URL = "https://qqtqtuzewywbpovifnfy.supabase.co"
SUPABASE_KEY = "sb_publishable_6bYGsd9Rmtmlk8-hV9bIhw_EINhceUd"

# Optional: Add OpenAI key if you want AI-powered note generation
# OPENAI_API_KEY = "your-openai-key-here"
